In [1]:
import pandas as pd

data = [
    [1, 1, "2019-07-20", "open_session"],
    [1, 1, "2019-07-20", "scroll_down"],
    [1, 1, "2019-07-20", "end_session"],
    [2, 4, "2019-07-20", "open_session"],
    [2, 4, "2019-07-21", "send_message"],
    [2, 4, "2019-07-21", "end_session"],
    [3, 2, "2019-07-21", "open_session"],
    [3, 2, "2019-07-21", "send_message"],
    [3, 2, "2019-07-21", "end_session"],
    [4, 3, "2019-06-25", "open_session"],
    [4, 3, "2019-06-25", "end_session"]
]

activity = pd.DataFrame(data, columns=[
    "user_id", "session_id", "activity_date", "activity_type"
])

In [7]:
import pandas as pd

def user_activity(activity: pd.DataFrame) -> pd.DataFrame:

    activity['activity_date'] = pd.to_datetime(activity['activity_date'])

    end_date = pd.to_datetime('2019-07-27')
    start_date = end_date - pd.Timedelta(days=30)

    filtered = activity[
        (activity['activity_date'] >= start_date) &
        (activity['activity_date'] <= end_date)
    ]

    result = filtered.groupby('activity_date')['user_id'].nunique().reset_index()

    result.columns = ['day', 'active_users']

    return result

In [8]:
activity

    user_id  session_id activity_date activity_type
0         1           1    2019-07-20  open_session
1         1           1    2019-07-20   scroll_down
2         1           1    2019-07-20   end_session
3         2           4    2019-07-20  open_session
4         2           4    2019-07-21  send_message
5         2           4    2019-07-21   end_session
6         3           2    2019-07-21  open_session
7         3           2    2019-07-21  send_message
8         3           2    2019-07-21   end_session
9         4           3    2019-06-25  open_session
10        4           3    2019-06-25   end_session

In [11]:
user_activity(activity)

         day  active_users
0 2019-07-20             2
1 2019-07-21             2